### ISSUE TITLE
Crash on RmpPanel.Paint

### ISSUE THREAD

**Issue by pmprog** [pmprog/OpenXCOM.Tools#8]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at XCom.Interfaces.Base.IMap_Base.get_Item(Int32 row, Int32 col, Int32 height)
   at XCom.Interfaces.Base.IMap_Base.get_Item(Int32 row, Int32 col)
   at MapView.RmpViewForm.RmpPanel.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer, Boolean disposeEventArgs)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
##     CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

MapView
    Assembly Version: 1.12.0.0
    Win32 Version: 1.12.0.0
##     CodeBase: file:///C:/Documents%20and%20Settings/Owner/Desktop/mapview/MapView.exe

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.1433 (REDBITS.050727-1400)
##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

XCom
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Documents%20and%20Settings/Owner/Desktop/mapview/XCom.DLL

DSShared
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Documents%20and%20Settings/Owner/Desktop/mapview/DSShared.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pmprog** [comment]
Added error handling, though not sure what the actual problem is yet, but at least it won't crash
